### PR TITLE
SGD8-1102: Updated theming for links in 'Mijn Gent' block

### PR DESCRIPTION
**Pull request by hstandaert**
## Motivation and Context

Inconsistency with the design (https://zpl.io/adAWBqR)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [x] I have updated the styleguide CHANGELOG accordingly.

### CODE REVIEW

**Review by delrueba — CHANGES_REQUESTED** [review]
I'm sorry, but this is bad practice for accessibility.
Pretty sure this block was reviewed and approved with underlined links.

**Comment by hstandaert** [comment]
> I'm sorry, but this is bad practice for accessibility.
> Pretty sure this block was reviewed and approved with underlined links.

Shouldn't we fix this on a higher level, then? This link styling is also applied to the menu and tabs and thus not accessible there either.

@mattiasberlamont, any suggestions? (also for the menu and tabs)

**Comment by delrueba** [comment]
> > I'm sorry, but this is bad practice for accessibility.
> > Pretty sure this block was reviewed and approved with underlined links.
> 
> Shouldn't we fix this on a higher level, then? This link styling is also applied to the menu and tabs and thus not accessible there either.
> 
> @mattiasberlamont, any suggestions? (also for the menu and tabs)

Menus and tabs form an exception to the whole 'color alone' rule, because of their placing, general layout etc.

That being said, there's definitely room for debate on this one, but there was a reason they were underlined.

**Comment by mattiasberlamont** [comment]
This dropdown is also a menu so no need for underlined links. As seen in the design.

**Review by delrueba — APPROVED** [review]

**Comment by delrueba** [comment]
Alright, as long as thought has been given to the matter I'm happy.

**Pull request merged**
