### PR TITLE
hotfix/3.0.0-beta2

### PR DESCRIPTION
**Pull request by hstandaert**
## Description

> ⚠️  **NOTE:** Would be useful if reviewers also test this on their machine.
* Removed all vulnerabilities for all dependencies, except for 1:

screenshot 2019-03-06 at 15 33 28
_Since this is a vulnerability of a optional dependency, we won't be focusing on it._

* Refactored components since we use another package as twig adapter, namely [frctl/twig](https://github.com/frctl/twig#included-tags).

	* `{% include ... %}` becomes {% render ... %}
	* Context is inherited in the `{% render ... %}` tag, which means some properties have to be set to `false` to avoid inheritance when unwanted.
	* the `view` property is no longer supported for variants (see `image-gallery`)
	* `variable|path` throws an error in nested templates, so all these twig filters were removed.

* Removed `contact-box` component (with [the styleguide components' analysis](https://digipolisgent.atlassian.net/wiki/spaces/UXWEB/pages/1101726698/Analyse+Stijlgids+componenten) in mind)

## How Has This Been Tested?

Local environment.

|  | Version |
|------|---------|
| node | 10.14.2 |
| yarn | 1.13.0 |

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have updated the documentation accordingly.
- [x] I have updated the styleguide CHANGELOG accordingly.
- [x] I have ran gulp axe on the compiled files and found no errors.

### CODE REVIEW

**Review by meirege — APPROVED** [review]
That's one hell of a PR. :P

**Comment by delrueba** [comment]
Logged an issue on gulp-axe-webdriver for this fs-path vulnerability.

**Review by delrueba — CHANGES_REQUESTED** [review]
I'd strongly recommend using 'null' instead of 'false' as 'false' holds a value and 'null' explicitly does not.
I'll make the changes in a commit.

**Review by delrueba — APPROVED** [review]

**Review by delrueba — CHANGES_REQUESTED** [review]
The checkbox-with filter is broken in filter layout, compared to qa.
(it's like too many columns are included)... not sure if this issue is related to this bugfix.

**Comment by hstandaert** [comment]
> The checkbox-with filter is broken in filter layout, compared to qa.
> (it's like too many columns are included)... not sure if this issue is related to this bugfix.

@delrueba I suppose this is related to the refactoring that has been done in [#598](https://github.com/StadGent/drupal_theme_gent-base/pull/598). Since then, the checkbox-with-filter component is a collated component and therefore uses another template. (i.e. the content isn't contained in a `.content-container` anymore).

**Comment by delrueba** [comment]
> > The checkbox-with filter is broken in filter layout, compared to qa.
> > (it's like too many columns are included)... not sure if this issue is related to this bugfix.
> 
> @delrueba I suppose this is related to the refactoring that has been done in [#598](https://github.com/StadGent/drupal_theme_gent-base/pull/598). Since then, the checkbox-with-filter component is a collated component and therefore uses another template. (i.e. the content isn't contained in a `.content-container` anymore).

Ah, we can make the layout stacked for now.
I've committed a basic fix.

**Review by delrueba — APPROVED** [review]

**Comment by hstandaert** [comment]
ℹ️ _Closed because the branch will be merged locally._

**Pull request closed without merging**
